# This is a basic workflow that is manually triggered

name: Additional Push

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.


on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-api-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Secret
        with: # Set API secret as an input
          credentials: ${{ secrets.REDOCLY_API_KEY }}
          env: # Or as an environment variable
            credentials: ${{ secrets.REDOCLY_API_KEY }}

      - name: Install dependencies
        run: |
          npm install redoc-cli
          npm install -g redoc-cli
          npm i -g @redocly/cli@latest
          sudo snap install yq --channel=v3/stable
      - name: Get the Documentation Yaml File
        run: |
          curl -o doc.json https://api.sandbox.overledger.io/v2/documentation/service/Overledger%20Core%20API/
          yq r -j doc.json > openapi.yaml
      - name: Build and publish API documentation
        env:
          REDOCLY_AUTHORIZATION: ${{env.credentials}}
        run: |
          npx @redocly/cli@latest push openapi.yaml "@test-redocly-s28/manualPush@v1"
