# This is a basic workflow to help you get started with Actions

name: CI_V3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install redoc-cli
          npm install -g redoc-cli
          npm i -g @redocly/cli@latest
          sudo snap install yq --channel=v3/stable
      - name: Generate token
        run: |
          curl -X POST -u "r0ha1jskkoeus11vm5616timb:ievds2o7vmc22drlns0st2d6kaf4qk0p05qa17iq31f771rocg4" -d "grant_type=client_credentials" https://sb-use1-overledger-1.auth.us-east-1.amazoncognito.com/token | jq -r '.access_token'
      - name: Get the Documentation Yaml File
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs }}
        run: |
          curl -o doc.json https://api.sandbox.overledger.io/documentation/ --header 'Authorization: Bearer ${{ steps.generate_token.outputs.access_token }}' 
          yq r -j doc.json > openapi.yaml
      - name: Build and publish API documentation
        env:
          REDOCLY_AUTHORIZATION: ${{ secrets.TEST_KEY }}
        run: |
          npx @redocly/cli@latest push openapi.yaml --destination="Test@v2" --organization="test-bjg"
